stages:
- name: build & push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: yswwhf/ngnix-demo:terry2v2
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./nginx-demo-terry2.yaml
timeout: 60
notification: {}
